import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "react-toastify";
import { apiFetch } from "../../services/api";
import { useAuth } from "../../context/useAuth";

const labels = { pending: "Pendiente", in_progress: "En curso", completed: "Completado", cancelled: "Cancelado", available: "Disponible", in_service: "En servicio", maintenance: "En taller", inactive: "Inactivo", active: "Activo", voided: "Anulado" };
const error = (value) => toast.error(value.message || "No se pudo completar la solicitud.");
const status = (value) => labels[value] || value || "-";
const date = (value) => {
  const [year, month, day] = String(value || "").slice(0, 10).split("-");
  return year ? `${day}/${month}/${year}` : "-";
};

const useCollection = (endpoint) => {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true);
  const refresh = useCallback(async () => { setLoading(true); try { setItems(await apiFetch(endpoint)); } catch (value) { error(value); } finally { setLoading(false); } }, [endpoint]);
  useEffect(() => { refresh(); }, [refresh]);
  return { items, loading, refresh };
};

function Header({ title, children }) { return <div className="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-4"><h1 className="h3 mb-0">{title}</h1>{children}</div>; }
function Loading({ loading }) { return <div className="card card-body text-muted">{loading ? "Cargando..." : "No hay datos."}</div>; }
function Field({ field, form, setForm, options = [] }) {
  if (field.when && !field.when(form)) return null;
  const value = form[field.name] ?? "";
  if (field.type === "select") return <select className="form-select mb-2" value={value} onChange={(event) => setForm({ ...form, [field.name]: event.target.value })} required={field.required}><option value="">{field.placeholder || "Seleccionar"}</option>{(field.options || options).map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>;
  if (field.type === "textarea") return <textarea className="form-control mb-2" placeholder={field.placeholder} value={value} onChange={(event) => setForm({ ...form, [field.name]: event.target.value })} required={field.required} />;
  return <input className="form-control mb-2" type={field.type || "text"} placeholder={field.placeholder} value={value} onChange={(event) => setForm({ ...form, [field.name]: event.target.value })} required={field.required} step={field.step} />;
}

function ResourcePage({ title, endpoint, fields, columns, prepare = (body) => body, dependencies = [] }) {
  const collection = useCollection(endpoint); const [form, setForm] = useState(Object.fromEntries(fields.map((field) => [field.name, field.initial ?? ""])));
  const submit = async (event) => { event.preventDefault(); try { await apiFetch(endpoint, { method: "POST", body: prepare(form) }); toast.success("Registro creado."); setForm(Object.fromEntries(fields.map((field) => [field.name, field.initial ?? ""]))); collection.refresh(); } catch (value) { error(value); } };
  return <><Header title={title} /><div className="row g-4"><div className="col-lg-4"><form className="card card-body shadow-sm" onSubmit={submit}><h2 className="h5">Nuevo registro</h2>{fields.map((field) => <Field key={field.name} field={{ ...field, options: field.options || (field.source ? dependencies.find((item) => item.name === field.source)?.options : []) }} form={form} setForm={setForm} />)}<button className="btn btn-primary">Guardar</button></form></div><div className="col-lg-8">{collection.loading ? <Loading loading /> : <div className="card shadow-sm table-responsive"><table className="table mb-0"><thead><tr>{columns.map((column) => <th key={column.label}>{column.label}</th>)}</tr></thead><tbody>{collection.items.map((item) => <tr key={item.id}>{columns.map((column) => <td key={column.label}>{column.value(item)}</td>)}</tr>)}</tbody></table></div>}</div></div></>;
}

function DashboardPage() {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setData(await apiFetch("/api/dashboard")); } catch (value) { error(value); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]); if (!data) return <Loading loading={loading} />;
  const cards = [["Viajes en curso", data.summary.activeTrips], ["Viajes pendientes", data.summary.pendingTrips], ["Camiones disponibles", data.summary.availableTrucks], ["Remolques disponibles", data.summary.availableTrailers], ["Unidades en taller", data.summary.vehiclesInWorkshop]];
  return <><Header title="Resumen operativo"><button className="btn btn-outline-primary" onClick={load}>Actualizar</button></Header><div className="row g-3 mb-4">{cards.map(([name, value]) => <div className="col-sm-6 col-lg" key={name}><div className="card shadow-sm h-100"><div className="card-body"><div className="small text-muted">{name}</div><div className="display-6">{value}</div></div></div></div>)}</div><div className="row g-4"><div className="col-lg-6"><div className="card shadow-sm"><div className="card-header">Viajes en curso</div><ul className="list-group list-group-flush">{data.activeTrips.length ? data.activeTrips.map((trip) => <li className="list-group-item" key={trip.id}><strong>{trip.origin} - {trip.destination}</strong><br /><small>{trip.truck?.licensePlate || "Sin camion"} / {trip.trailer?.licensePlate} - {trip.driver?.fullName}</small></li>) : <li className="list-group-item text-muted">Sin viajes en curso.</li>}</ul></div></div><div className="col-lg-6"><div className="card shadow-sm"><div className="card-header">Consumo del último viaje con tickets asociados (km/l)</div><ul className="list-group list-group-flush">{data.fuelConsumption.length ? data.fuelConsumption.map((row) => <li className="list-group-item d-flex justify-content-between gap-3" key={row.vehicleId}><span><strong>{row.licensePlate}</strong><br /><small className="text-muted">{row.origin} - {row.destination} · {date(row.departureAt)}</small></span><strong className="text-nowrap">{Number(row.kmPerLiter).toFixed(2)} km/l</strong></li>) : <li className="list-group-item text-muted">Se requieren tickets asociados al viaje y dos lecturas crecientes de odómetro.</li>}</ul></div></div></div></>;
}

function VehiclesPage() { return <ResourcePage title="Vehiculos" endpoint="/api/vehiculos" fields={[{ name: "licensePlate", placeholder: "Matricula", required: true }, { name: "type", type: "select", initial: "truck", options: [{ value: "truck", label: "Camion" }, { value: "trailer", label: "Remolque" }], required: true }, { name: "brand", placeholder: "Marca" }, { name: "model", placeholder: "Modelo" }, { name: "status", type: "select", initial: "available", options: [{ value: "available", label: "Disponible" }, { value: "in_service", label: "En servicio" }, { value: "maintenance", label: "En taller" }, { value: "inactive", label: "Inactivo" }] }]} columns={[{ label: "Matricula", value: (item) => item.licensePlate }, { label: "Tipo", value: (item) => item.type === "truck" ? "Camion" : "Remolque" }, { label: "Estado", value: (item) => status(item.status) }, { label: "Chofer", value: (item) => item.currentDriver?.fullName || "-" }]} />; }
function DriversPage() { return <ResourcePage title="Choferes" endpoint="/api/choferes" fields={[{ name: "fullName", placeholder: "Nombre completo", required: true }, { name: "document", placeholder: "Documento", required: true }, { name: "phone", placeholder: "Telefono" }, { name: "licenseExpiresAt", type: "date", placeholder: "Vencimiento libreta" }, { name: "status", type: "select", initial: "active", options: [{ value: "active", label: "Activo" }, { value: "inactive", label: "Inactivo" }] }]} columns={[{ label: "Nombre", value: (item) => item.fullName }, { label: "Documento", value: (item) => item.document }, { label: "Telefono", value: (item) => item.phone || "-" }, { label: "Libreta", value: (item) => item.licenseExpiresAt || "-" }, { label: "Estado", value: (item) => status(item.status) }]} />; }

function LegacyTripsPage() {
  const vehicles = useCollection("/api/vehiculos"); const drivers = useCollection("/api/choferes");
  const sources = useMemo(() => [{ name: "trailer", options: vehicles.items.filter((item) => item.type === "trailer" && item.status === "available").map((item) => ({ value: item.id, label: item.licensePlate })) }, { name: "truck", options: vehicles.items.filter((item) => item.type === "truck" && item.status === "available").map((item) => ({ value: item.id, label: item.licensePlate })) }, { name: "driver", options: drivers.items.filter((item) => item.status === "active").map((item) => ({ value: item.id, label: item.fullName })) }], [vehicles.items, drivers.items]);
  return <ResourcePage title="Viajes" endpoint="/api/viajes" dependencies={sources} fields={[{ name: "trailerVehicleId", type: "select", source: "trailer", placeholder: "Remolque *", required: true }, { name: "truckVehicleId", type: "select", source: "truck", placeholder: "Camion (opcional al planificar)" }, { name: "driverId", type: "select", source: "driver", placeholder: "Chofer *", required: true }, { name: "origin", placeholder: "Origen", required: true }, { name: "destination", placeholder: "Destino", required: true }, { name: "departureAt", type: "date", required: true }, { name: "cargoType", type: "select", initial: "refrigerated", options: [{ value: "refrigerated", label: "Camara de frio" }, { value: "container", label: "Contenedor" }], required: true }, { name: "containerNumber", placeholder: "Numero de contenedor", when: (form) => form.cargoType === "container" }, { name: "rotation", placeholder: "Virada / rotacion" }, { name: "notes", type: "textarea", placeholder: "Notas" }]} prepare={(form) => ({ ...form, truckVehicleId: form.truckVehicleId || null, containerNumber: form.cargoType === "container" ? form.containerNumber : null, status: "pending" })} columns={[{ label: "Ruta", value: (item) => `${item.origin} - ${item.destination}` }, { label: "Camion", value: (item) => item.truck?.licensePlate || "Sin asignar" }, { label: "Remolque", value: (item) => item.trailer?.licensePlate }, { label: "Carga", value: (item) => item.cargoType === "container" ? `Contenedor ${item.containerNumber}` : "Camara de frio" }, { label: "Estado", value: (item) => status(item.status) }]} />;
}

function LegacyWorkOrdersPage() { const vehicles = useCollection("/api/vehiculos"); const sources = [{ name: "vehicle", options: vehicles.items.map((item) => ({ value: item.id, label: item.licensePlate })) }]; return <ResourcePage title="Ordenes de taller" endpoint="/api/ordenes-taller" dependencies={sources} fields={[{ name: "vehicleId", type: "select", source: "vehicle", placeholder: "Vehiculo *", required: true }, { name: "checkInAt", type: "date", required: true }, { name: "type", placeholder: "Tipo" }, { name: "odometer", type: "number", placeholder: "Odometro" }, { name: "description", type: "textarea", placeholder: "Descripcion *", required: true }]} prepare={(form) => ({ ...form, odometer: form.odometer ? Number(form.odometer) : null, status: "pending" })} columns={[{ label: "Vehiculo", value: (item) => item.vehicle?.licensePlate }, { label: "Ingreso", value: (item) => date(item.checkInAt) }, { label: "Descripcion", value: (item) => item.description }, { label: "Estado", value: (item) => status(item.status) }]} />; }
function FuelTicketsPage() { const vehicles = useCollection("/api/vehiculos"); const trips = useCollection("/api/viajes"); const sources = [{ name: "vehicle", options: vehicles.items.map((item) => ({ value: item.id, label: item.licensePlate })) }, { name: "trip", options: [{ value: "", label: "Sin viaje asociado" }, ...trips.items.map((item) => ({ value: item.id, label: `${item.origin} - ${item.destination}` }))] }]; return <ResourcePage title="Combustible" endpoint="/api/consumos" dependencies={sources} fields={[{ name: "vehicleId", type: "select", source: "vehicle", placeholder: "Vehiculo *", required: true }, { name: "tripId", type: "select", source: "trip", placeholder: "Viaje" }, { name: "occurredAt", type: "date", required: true }, { name: "liters", type: "number", step: "0.001", placeholder: "Litros *", required: true }, { name: "totalAmount", type: "number", step: "0.01", placeholder: "Importe total *", required: true }, { name: "supplier", placeholder: "Proveedor *", required: true }, { name: "odometer", type: "number", placeholder: "Odometro *", required: true }, { name: "notes", type: "textarea", placeholder: "Notas" }]} prepare={(form) => ({ ...form, tripId: form.tripId || null, liters: Number(form.liters), totalAmount: Number(form.totalAmount), odometer: Number(form.odometer) })} columns={[{ label: "Vehiculo", value: (item) => item.vehicle?.licensePlate }, { label: "Fecha", value: (item) => date(item.occurredAt) }, { label: "Litros", value: (item) => item.liters }, { label: "Importe", value: (item) => item.totalAmount }, { label: "Estado", value: (item) => status(item.status) }]} />; }

function AdminPage() {
  const { hasPermission } = useAuth(); const [organization, setOrganization] = useState(null); const [users, setUsers] = useState([]); const [roles, setRoles] = useState([]); const [audit, setAudit] = useState([]);
  const load = useCallback(async () => { try { const [org, usersData, rolesData, auditData] = await Promise.all([hasPermission("organization.read") ? apiFetch("/api/admin/organization") : null, hasPermission("users.manage") ? apiFetch("/api/admin/users") : [], hasPermission("roles.manage") ? apiFetch("/api/admin/roles") : [], hasPermission("audit.read") ? apiFetch("/api/admin/organization/audit") : []]); setOrganization(org); setUsers(usersData); setRoles(rolesData); setAudit(auditData); } catch (value) { error(value); } }, [hasPermission]);
  useEffect(() => { load(); }, [load]);
  return <><Header title="Administracion de organizacion" />{organization && <div className="card card-body shadow-sm mb-4"><strong>{organization.name}</strong><span className="text-muted">Plan {organization.planCode} · {status(organization.status)}</span></div>}<div className="row g-4"><div className="col-lg-7"><div className="card shadow-sm table-responsive"><div className="card-header">Usuarios</div><table className="table mb-0"><thead><tr><th>Nombre</th><th>Email</th><th>Estado</th><th>Roles</th></tr></thead><tbody>{users.map((item) => <tr key={item.id}><td>{item.fullName}</td><td>{item.email}</td><td>{status(item.status)}</td><td>{item.roles.map((role) => role.name).join(", ") || "-"}</td></tr>)}</tbody></table></div></div><div className="col-lg-5"><div className="card card-body shadow-sm"><h2 className="h5">Roles configurados</h2>{roles.map((role) => <div className="border-bottom py-2" key={role.id}><strong>{role.name}</strong><br /><small>{role.permissions.map((permission) => permission.code).join(", ")}</small></div>)}</div></div><div className="col-12"><div className="card shadow-sm"><div className="card-header">Auditoria reciente</div><ul className="list-group list-group-flush">{audit.slice(0, 20).map((entry) => <li className="list-group-item" key={entry.id}><strong>{entry.action}</strong> · {entry.actor?.fullName || "Sistema"} · {date(entry.createdAt)}</li>)}</ul></div></div></div></>;
}

export { DashboardPage, VehiclesPage, DriversPage, LegacyTripsPage, LegacyWorkOrdersPage, FuelTicketsPage, AdminPage };
